### ISSUE TITLE
using Dataloader to query InfluxDB

### ISSUE THREAD

**Issue by chemmex** [nileio/node-red-contrib-graphql-server#16]
Hi, I'm trying to make use of DataLoader option in my not so common configuration: 
I have two resolvers: first one queries Mongo for a set of Ids of variable length, second one gets those Ids through the parent object and then queries InfluxDB. An array of Ids gets converted to a single string Influx query which returns aggregated result, so the payload is a single value rather than array with the same set of keys.
Expectedly, graphql-out node complains that resulting array differs in length from array of keys and refuses to parse the payload.

Is there a way to handle such situation with Dataloader or I should find another approach?

**Comment by nileio** [comment]
hi @chemmex you would need to return the same length as the parent array. I usually either use Jsonata or a function to iterate through the results coming from a database, then ensure that you return something for each key in the parent array.
This is how Dataloader works at current implementation which does not use an `id` field per sa because we don't know what field is an id field. However with DataLoader an array should always be returned , and items in the array should correspond to the parent. Hope this makes sense.
Can you share part or examples of the data of your flow?
Using `graphql.parent` & `graphql.return` you can find out everything required at run-time to return the results using graphql out. I dont know how your objects are coming back from the databases so cant make suggestion

**Comment by nileio** [comment]
@chemmex can I close this issue now?

**Comment by chemmex** [comment]
Yes, sure. Though I am wondering how I can construct the function to fake the results for GraphQL-out node while keeping my aggregated result. Return N copies of the aggregate value?

**Comment by nileio** [comment]
@chemmex you got to share examples of what the data structure look like. you will need to use a function node or a change node to build the output structure in the required format. This is not a limitation of the node itself or Dataloader, this is how GraphQL requires it in order to build the return back to the client.
